apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-clusters-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/your-org/gitops-repo.git'
        revision: main
        directories:
          - path: clusters/hub-clusters/*-values.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-org/remote-helm-charts.git'
        targetRevision: main
        chart: hub-infrastructure-chart
        helm:
          valueFiles:
            - '{{path}}'                  # Override values from hub cluster-specific YAML
            - global-values/values.yaml  # Include global values
      destination:
        server: https://kubernetes.default.svc
        namespace: hub-cluster-namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true