apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sites-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/your-org/gitops-repo.git'
        revision: main
        directories:
          - path: sites/*.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-org/gitops-repo.git'
        targetRevision: main
        path: sites
      destination:
        server: https://kubernetes.default.svc
        namespace: site-namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true